"""empty message

Revision ID: e2d15ce6f8ac
Revises: 
Create Date: 2026-03-22 20:19:14.416000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d15ce6f8ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('birthdate', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('allergies', sa.String(length=600), nullable=False),
    sa.PrimaryKeyConstraint('dni')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('rol', sa.String(length=55), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id_patient', sa.String(), nullable=True),
    sa.Column('id_doctor', sa.Integer(), nullable=True),
    sa.Column('id_nurse', sa.Integer(), nullable=True),
    sa.Column('visitreason', sa.String(length=600), nullable=False),
    sa.Column('valoration_triage', sa.String(length=600), nullable=True),
    sa.Column('triage_priority', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checkpoint_triage', sa.Integer(), nullable=True),
    sa.Column('checkpoint_consult', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_doctor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_nurse'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.dni'], ),python_version
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalize_test', sa.Integer(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('incidents', sa.Text(), nullable=True),
    sa.Column('results', sa.String(length=600), nullable=True),
    sa.Column('id_income', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_income'], ['income.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('income')
    op.drop_table('user')
    op.drop_table('patient')
    # ### end Alembic commands ###
